-- ================================================================
-- MES系统 Oracle 数据库表结构
-- 半导体行业生产执行系统
-- 创建时间: 2025-10-30
-- ================================================================

-- 创建设备表
CREATE TABLE MES_EQUIPMENT (
    EQUIPMENT_ID VARCHAR2(50) PRIMARY KEY,
    EQUIPMENT_NAME VARCHAR2(100) NOT NULL,
    EQUIPMENT_TYPE VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CURRENT_LOT_ID VARCHAR2(50),
    LAST_UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 创建批次表
CREATE TABLE MES_WAFER_LOTS (
    LOT_ID VARCHAR2(50) PRIMARY KEY,
    PRODUCT_ID VARCHAR2(50) NOT NULL,
    PRODUCT_NAME VARCHAR2(100) NOT NULL,
    WAFER_COUNT NUMBER(5) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    CURRENT_EQUIPMENT VARCHAR2(50),
    CURRENT_PROCESS VARCHAR2(50),
    LAST_UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 创建生产数据表
CREATE TABLE MES_PRODUCTION_DATA (
    DATA_ID NUMBER(10) PRIMARY KEY,
    LOT_ID VARCHAR2(50) NOT NULL,
    EQUIPMENT_ID VARCHAR2(50) NOT NULL,
    PROCESS_STEP_ID VARCHAR2(50),
    START_TIME TIMESTAMP NOT NULL,
    END_TIME TIMESTAMP,
    STATUS VARCHAR2(20) NOT NULL,
    RESULT VARCHAR2(50),
    OPERATOR_ID VARCHAR2(50),
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 创建序列
CREATE SEQUENCE SEQ_MES_DATA_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 创建测量数据表
CREATE TABLE MES_MEASUREMENTS (
    MEASUREMENT_ID NUMBER(10) PRIMARY KEY,
    DATA_ID NUMBER(10),
    LOT_ID VARCHAR2(50) NOT NULL,
    PARAMETER_NAME VARCHAR2(100) NOT NULL,
    PARAMETER_VALUE NUMBER(10,4),
    MEASUREMENT_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 创建测量数据序列
CREATE SEQUENCE SEQ_MES_MEASUREMENT_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 创建报警表
CREATE TABLE MES_ALARMS (
    ALARM_ID VARCHAR2(50) PRIMARY KEY,
    EQUIPMENT_ID VARCHAR2(50) NOT NULL,
    LOT_ID VARCHAR2(50),
    ALARM_CODE VARCHAR2(50) NOT NULL,
    ALARM_MESSAGE VARCHAR2(200) NOT NULL,
    SEVERITY VARCHAR2(20) NOT NULL,
    OCCUR_TIME TIMESTAMP NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'ACTIVE',
    CLEAR_TIME TIMESTAMP,
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 创建批次追踪表
CREATE TABLE MES_LOT_TRACKING (
    TRACKING_ID NUMBER(10) PRIMARY KEY,
    LOT_ID VARCHAR2(50) NOT NULL,
    EQUIPMENT_ID VARCHAR2(50) NOT NULL,
    PROCESS_STEP_ID VARCHAR2(50),
    IN_TIME TIMESTAMP NOT NULL,
    OUT_TIME TIMESTAMP,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 创建批次追踪序列
CREATE SEQUENCE SEQ_MES_TRACKING_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 创建质量数据表
CREATE TABLE MES_QUALITY_DATA (
    QUALITY_ID NUMBER(10) PRIMARY KEY,
    LOT_ID VARCHAR2(50) NOT NULL,
    WAFER_ID VARCHAR2(50),
    TEST_ID VARCHAR2(50) NOT NULL,
    YIELD NUMBER(10,4),
    TEST_TIME TIMESTAMP NOT NULL,
    RESULT VARCHAR2(50),
    CREATED_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- 创建质量数据序列
CREATE SEQUENCE SEQ_MES_QUALITY_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 创建设备状态历史表
CREATE TABLE MES_EQUIPMENT_HISTORY (
    HISTORY_ID NUMBER(10) PRIMARY KEY,
    EQUIPMENT_ID VARCHAR2(50) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    LOT_ID VARCHAR2(50),
    CHANGE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP,
    OPERATOR_ID VARCHAR2(50)
);

-- 创建设备历史序列
CREATE SEQUENCE SEQ_MES_EQUIPMENT_HISTORY_ID
    START WITH 1
    INCREMENT BY 1
    NOCACHE;

-- 插入示例数据
-- 插入设备
INSERT INTO MES_EQUIPMENT (EQUIPMENT_ID, EQUIPMENT_NAME, EQUIPMENT_TYPE, STATUS) VALUES ('EQ001', '光刻机1号', 'LITHOGRAPHY', 'IDLE');
INSERT INTO MES_EQUIPMENT (EQUIPMENT_ID, EQUIPMENT_NAME, EQUIPMENT_TYPE, STATUS) VALUES ('EQ002', '蚀刻机1号', 'ETCH', 'IDLE');
INSERT INTO MES_EQUIPMENT (EQUIPMENT_ID, EQUIPMENT_NAME, EQUIPMENT_TYPE, STATUS) VALUES ('EQ003', '薄膜沉积1号', 'DEPOSITION', 'IDLE');
INSERT INTO MES_EQUIPMENT (EQUIPMENT_ID, EQUIPMENT_NAME, EQUIPMENT_TYPE, STATUS) VALUES ('EQ004', '离子注入1号', 'IMPLANT', 'IDLE');
INSERT INTO MES_EQUIPMENT (EQUIPMENT_ID, EQUIPMENT_NAME, EQUIPMENT_TYPE, STATUS) VALUES ('EQ005', '化学气相沉积1号', 'CVD', 'IDLE');

-- 插入批次
INSERT INTO MES_WAFER_LOTS (LOT_ID, PRODUCT_ID, PRODUCT_NAME, WAFER_COUNT, STATUS) VALUES ('LOT123', 'PROD001', '12寸晶圆A型', 25, 'IN_QUEUE');
INSERT INTO MES_WAFER_LOTS (LOT_ID, PRODUCT_ID, PRODUCT_NAME, WAFER_COUNT, STATUS) VALUES ('LOT124', 'PROD002', '8寸晶圆B型', 20, 'IN_QUEUE');
INSERT INTO MES_WAFER_LOTS (LOT_ID, PRODUCT_ID, PRODUCT_NAME, WAFER_COUNT, STATUS) VALUES ('LOT125', 'PROD001', '12寸晶圆A型', 25, 'IN_QUEUE');

-- 提交更改
COMMIT;

-- 创建索引
CREATE INDEX IDX_MES_LOT_EQUIPMENT ON MES_WAFER_LOTS(CURRENT_EQUIPMENT);
CREATE INDEX IDX_MES_ALARMS_EQUIPMENT ON MES_ALARMS(EQUIPMENT_ID);
CREATE INDEX IDX_MES_ALARMS_TIME ON MES_ALARMS(OCCUR_TIME);
CREATE INDEX IDX_MES_TRACKING_LOT ON MES_LOT_TRACKING(LOT_ID);
CREATE INDEX IDX_MES_PRODUCTION_LOT ON MES_PRODUCTION_DATA(LOT_ID);
CREATE INDEX IDX_MES_MEASUREMENTS_LOT ON MES_MEASUREMENTS(LOT_ID);

-- 创建视图
CREATE OR REPLACE VIEW MES_V_ACTIVE_LOTS AS
SELECT
    L.LOT_ID,
    L.PRODUCT_NAME,
    L.WAFER_COUNT,
    L.STATUS,
    E.EQUIPMENT_NAME AS CURRENT_EQUIPMENT,
    L.LAST_UPDATE_TIME
FROM MES_WAFER_LOTS L
LEFT JOIN MES_EQUIPMENT E ON L.CURRENT_EQUIPMENT = E.EQUIPMENT_ID
WHERE L.STATUS IN ('IN_PROCESS', 'IN_QUEUE');

CREATE OR REPLACE VIEW MES_V_EQUIPMENT_STATUS AS
SELECT
    E.EQUIPMENT_ID,
    E.EQUIPMENT_NAME,
    E.EQUIPMENT_TYPE,
    E.STATUS,
    E.CURRENT_LOT_ID,
    L.PRODUCT_NAME,
    E.LAST_UPDATE_TIME
FROM MES_EQUIPMENT E
LEFT JOIN MES_WAFER_LOTS L ON E.CURRENT_LOT_ID = L.LOT_ID;

CREATE OR REPLACE VIEW MES_V_ALARM_SUMMARY AS
SELECT
    EQUIPMENT_ID,
    COUNT(*) AS TOTAL_ALARMS,
    COUNT(CASE WHEN SEVERITY = 'CRITICAL' THEN 1 END) AS CRITICAL_COUNT,
    COUNT(CASE WHEN SEVERITY = 'WARNING' THEN 1 END) AS WARNING_COUNT,
    MAX(OCCUR_TIME) AS LAST_OCCUR_TIME
FROM MES_ALARMS
WHERE STATUS = 'ACTIVE'
GROUP BY EQUIPMENT_ID;

-- 创建存储过程示例
CREATE OR REPLACE PROCEDURE SP_UPDATE_EQUIPMENT_STATUS(
    p_equipment_id IN VARCHAR2,
    p_status IN VARCHAR2,
    p_lot_id IN VARCHAR2 DEFAULT NULL
) AS
BEGIN
    UPDATE MES_EQUIPMENT
    SET
        STATUS = p_status,
        CURRENT_LOT_ID = p_lot_id,
        LAST_UPDATE_TIME = SYSTIMESTAMP
    WHERE EQUIPMENT_ID = p_equipment_id;

    INSERT INTO MES_EQUIPMENT_HISTORY (HISTORY_ID, EQUIPMENT_ID, STATUS, LOT_ID, CHANGE_TIME)
    VALUES (SEQ_MES_EQUIPMENT_HISTORY_ID.NEXTVAL, p_equipment_id, p_status, p_lot_id, SYSTIMESTAMP);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_UPDATE_EQUIPMENT_STATUS;
/

-- 创建触发器示例
CREATE OR REPLACE TRIGGER TR_MES_LOT_STATUS_CHANGE
    AFTER UPDATE OF STATUS ON MES_WAFER_LOTS
    FOR EACH ROW
BEGIN
    IF :NEW.STATUS != :OLD.STATUS THEN
        INSERT INTO MES_LOT_TRACKING (TRACKING_ID, LOT_ID, EQUIPMENT_ID, STATUS, IN_TIME)
        VALUES (SEQ_MES_TRACKING_ID.NEXTVAL, :NEW.LOT_ID, :NEW.CURRENT_EQUIPMENT, :NEW.STATUS, SYSTIMESTAMP);
    END IF;
END;
/

-- 创建包示例
CREATE OR REPLACE PACKAGE PKG_MES_EQUIPMENT AS
    PROCEDURE GET_EQUIPMENT_STATUS(p_cursor OUT SYS_REFCURSOR);
    FUNCTION GET_ACTIVE_LOTS RETURN SYS_REFCURSOR;
    PROCEDURE LOG_ALARM(p_equipment_id IN VARCHAR2, p_alarm_code IN VARCHAR2, p_message IN VARCHAR2, p_severity IN VARCHAR2);
END PKG_MES_EQUIPMENT;
/

CREATE OR REPLACE PACKAGE BODY PKG_MES_EQUIPMENT AS
    PROCEDURE GET_EQUIPMENT_STATUS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN
        OPEN p_cursor FOR
        SELECT * FROM MES_V_EQUIPMENT_STATUS ORDER BY EQUIPMENT_ID;
    END;

    FUNCTION GET_ACTIVE_LOTS RETURN SYS_REFCURSOR IS
        l_cursor SYS_REFCURSOR;
    BEGIN
        OPEN l_cursor FOR
        SELECT * FROM MES_V_ACTIVE_LOTS ORDER BY LAST_UPDATE_TIME DESC;
        RETURN l_cursor;
    END;

    PROCEDURE LOG_ALARM(p_equipment_id IN VARCHAR2, p_alarm_code IN VARCHAR2, p_message IN VARCHAR2, p_severity IN VARCHAR2) IS
        v_alarm_id VARCHAR2(50);
    BEGIN
        v_alarm_id := 'ALM_' || TO_CHAR(SYSTIMESTAMP, 'YYYYMMDDHH24MISS') || '_' || p_equipment_id;

        INSERT INTO MES_ALARMS (ALARM_ID, EQUIPMENT_ID, ALARM_CODE, ALARM_MESSAGE, SEVERITY, OCCUR_TIME, STATUS)
        VALUES (v_alarm_id, p_equipment_id, p_alarm_code, p_message, p_severity, SYSTIMESTAMP, 'ACTIVE');

        COMMIT;
    END;
END PKG_MES_EQUIPMENT;
/

-- 授权示例
GRANT SELECT, INSERT, UPDATE, DELETE ON MES_EQUIPMENT TO MES_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON MES_WAFER_LOTS TO MES_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON MES_PRODUCTION_DATA TO MES_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON MES_MEASUREMENTS TO MES_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON MES_ALARMS TO MES_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON MES_LOT_TRACKING TO MES_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON MES_QUALITY_DATA TO MES_USER;

GRANT EXECUTE ON PKG_MES_EQUIPMENT TO MES_USER;

COMMENT ON TABLE MES_EQUIPMENT IS '设备主数据表';
COMMENT ON TABLE MES_WAFER_LOTS IS '晶圆批次主表';
COMMENT ON TABLE MES_PRODUCTION_DATA IS '生产数据表';
COMMENT ON TABLE MES_MEASUREMENTS IS '工艺测量数据表';
COMMENT ON TABLE MES_ALARMS IS '设备报警表';
COMMENT ON TABLE MES_LOT_TRACKING IS '批次追踪记录表';
COMMENT ON TABLE MES_QUALITY_DATA IS '质量数据表';

-- ================================================================
-- 数据库创建完成
-- ================================================================
